# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '球队', 'verbose_name_plural': '球队'},
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
    ]
